-- init.sql
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
    CREATE USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
  END IF;
END $$;

CREATE DATABASE ${POSTGRES_DB} WITH OWNER ${POSTGRES_USER};

GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};

\c ${POSTGRES_DB}

CREATE SCHEMA IF NOT EXISTS drone_schema AUTHORIZATION ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON SCHEMA drone_schema TO ${POSTGRES_USER};
ALTER ROLE ${POSTGRES_USER} SET search_path TO drone_schema, public;