"""initial migration

Revision ID: 5a488e504cff
Revises: d52c852df4c9
Create Date: 2025-07-02 14:06:06.837100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a488e504cff'
down_revision: Union[str, Sequence[str], None] = 'd52c852df4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_drone', sa.Boolean(), nullable=True),
    sa.Column('is_shaheed', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('audio_sample_path', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('drone_type', sa.String(), nullable=True),
    sa.Column('spectral_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_events_id'), 'detection_events', ['id'], unique=False)
    op.create_table('gnss_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('gps_sats', sa.Integer(), nullable=True),
    sa.Column('glonass_sats', sa.Integer(), nullable=True),
    sa.Column('galileo_sats', sa.Integer(), nullable=True),
    sa.Column('beidou_sats', sa.Integer(), nullable=True),
    sa.Column('snr_values', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gnss_data_id'), 'gnss_data', ['id'], unique=False)
    op.create_table('jamming_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('affected_systems', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jamming_events_id'), 'jamming_events', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('frequency_range', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_jamming_events_id'), table_name='jamming_events')
    op.drop_table('jamming_events')
    op.drop_index(op.f('ix_gnss_data_id'), table_name='gnss_data')
    op.drop_table('gnss_data')
    op.drop_index(op.f('ix_detection_events_id'), table_name='detection_events')
    op.drop_table('detection_events')
    # ### end Alembic commands ###
